In [1]:
practial 1
#integer
a=25
type(a)
print(type(a))
#float
a=3.5
print(type(a))
#string
name="Isai"
print(type(name))
#Boolean
is_teacher=True
print(type(is_teacher))
#List
num=["one","two","three"]
print(type(num))
#Tuple
val=(26,45,67)
print(type(val))
#dictonary
marks={"maths":"75","tamil":"90"}
print(type(marks))
#set
num={45,50,55,60}
print(type(num))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'set'>


In [3]:
practical 2
# if
num1 = int(input("Enter a number: "))
if num1 > 0:
    print("The number is Positive")
else:
    print("The number is Zero or Negative")

#if-else
num2 = int(input("Enter another number: "))
if num2 % 2 == 0:
    print("The number is Even")
else:
    print("The number is Odd")

#if-elif-else
marks = int(input("Enter student marks: "))
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")
#nested if-else
username = input("Enter username: ")
password = input("Enter password: ")
if username == "admin":
    if password == "1234":
        print("Login Successful")
    else:
        print("Incorrect Password")
else:
    print("Incorrect Username")

#one-line if-else
age = int(input("Enter your age: "))
print("Eligible to Vote") if age >= 18 else print("Not Eligible to Vote")

#For loop 1 to 5
print("Numbers using for loop:")
for i in range(1, 6):
    print(i, end=" ")

#While loop 1 to 5
print("\nNumbers using while loop:")
i = 1
while i <= 5:
    print(i, end=" ")
    i += 1

#Break statement
print("\nBreak demo:")
for i in range(1, 10):
    if i == 5:
        break
    print(i, end=" ")

#Continue statement
print("\nContinue demo:")
for i in range(1, 10):
    if i == 5:
        continue
    print(i, end=" ")

#Pass statement
print("\nPass demo:")
for i in range(1, 4):
    if i == 2:
        pass
    print(i, end=" ")

#Match-case for day
print("\n")
day = int(input("Enter day number 1-7: "))
match day:
    case 1: print("Monday")
    case 2: print("Tuesday")
    case 3: print("Wednesday")
    case 4: print("Thursday")
    case 5: print("Friday")
    case 6: print("Saturday")
    case 7: print("Sunday")
    case _: print("Invalid Day")

print("Program Ended")

Enter a number:  -35


The number is Zero or Negative


Enter another number:  66


The number is Even


Enter student marks:  75


Grade: B


Enter username:  admin
Enter password:  2345


Incorrect Password


Enter your age:  18


Eligible to Vote
Numbers using for loop:
1 2 3 4 5 
Numbers using while loop:
1 2 3 4 5 
Break demo:
1 2 3 4 
Continue demo:
1 2 3 4 6 7 8 9 
Pass demo:
1 2 3 



Enter day number 1-7:  3


Wednesday
Program Ended


In [4]:
practical 3
# 1. No arguments, No return value
def greet():
    print("Hello!")

greet()

# 2. Arguments, No return value
def add(a, b):
    print("Sum =", a + b)

add(10, 20)

# 3. No arguments, Return value
def message():
    return "Welcome to Python"

print(message())

# 4. Arguments, Return value
def multiply(a, b):
    return a * b

print("Product =", multiply(5, 4))

# 5. Default argument
def student(name="Dharshini"):
    print("Name:", name)

student()
student("Ravi")

# 6. Keyword arguments
def details(name, age):
    print("Name:", name)
    print("Age:", age)

details(age=18, name="Anu")

# 7. Variable length arguments
def total(*marks):
    print("Total Marks =", sum(marks))

total(80, 90, 85)

# 8. Lambda function
square = lambda x: x * x
print("Square =", square(5))

# 9. Recursive function
def fact(n):
    if n == 1:
        return 1
    return n * fact(n - 1)

print("Factorial =", fact(5))

# 10. Nested function
def outer():
    def inner():
        print("Inner Function")
    inner()

outer()

Hello!
Sum = 30
Welcome to Python
Product = 20
Name: Dharshini
Name: Ravi
Name: Anu
Age: 18
Total Marks = 255
Square = 25
Factorial = 120
Inner Function


In [5]:
practical 4
# Create a list
nums = [1, 2, 3, 4, 5]

print("Original List:", nums)
print("First Element:", nums[0])
print("Last Element:", nums[-1])

# Append
nums.append(6)
print("After Append:", nums)

# Insert
nums.insert(2, 10)
print("After Insert:", nums)

# Remove
nums.remove(10)
print("After Remove:", nums)

# Length
print("Length:", len(nums))

# Traverse
print("List Elements:")
for i in nums:
    print(i)

# List Comprehension
square = [x*x for x in nums]
even = [x for x in nums if x % 2 == 0]
odd = [x for x in nums if x % 2 != 0]
double = [x*2 for x in nums]

matrix = [[1, 2], [3, 4]]
flat = [x for row in matrix for x in row]

print("Squares:", square)
print("Even:", even)
print("Odd:", odd)
print("Double:", double)
print("Flattened List:", flat)

Original List: [1, 2, 3, 4, 5]
First Element: 1
Last Element: 5
After Append: [1, 2, 3, 4, 5, 6]
After Insert: [1, 2, 10, 3, 4, 5, 6]
After Remove: [1, 2, 3, 4, 5, 6]
Length: 6
List Elements:
1
2
3
4
5
6
Squares: [1, 4, 9, 16, 25, 36]
Even: [2, 4, 6]
Odd: [1, 3, 5]
Double: [2, 4, 6, 8, 10, 12]
Flattened List: [1, 2, 3, 4]


In [6]:
practical 5
# Tuple
t = (10, 20, 30, 40, 20)

print("Tuple:", t)
print("First Element:", t[0])
print("Last Element:", t[-1])
print("Length:", len(t))
print("Slicing:", t[1:4])
print("Count of 20:", t.count(20))
print("Index of 30:", t.index(30))

print("Tuple Elements:")
for i in t:
    print(i)

t2 = (50, 60)
print("Concatenated Tuple:", t + t2)

# Set
s = {1, 2, 3, 4}

print("Original Set:", s)

s.add(5)
print("After Add:", s)

s.remove(2)
print("After Remove:", s)

print("Length:", len(s))

print("Set Elements:")
for i in s:
    print(i)

s2 = {3, 4, 5, 6}

print("Union:", s | s2)
print("Intersection:", s & s2)
print("Difference:", s - s2)
print("Symmetric Difference:", s ^ s2)

Tuple: (10, 20, 30, 40, 20)
First Element: 10
Last Element: 20
Length: 5
Slicing: (20, 30, 40)
Count of 20: 2
Index of 30: 2
Tuple Elements:
10
20
30
40
20
Concatenated Tuple: (10, 20, 30, 40, 20, 50, 60)
Original Set: {1, 2, 3, 4}
After Add: {1, 2, 3, 4, 5}
After Remove: {1, 3, 4, 5}
Length: 4
Set Elements:
1
3
4
5
Union: {1, 3, 4, 5, 6}
Intersection: {3, 4, 5}
Difference: {1}
Symmetric Difference: {1, 6}


In [12]:
practical 6
# Dictionary Operations

student = {
    "Name": "priyadharshini",
    "Age": 18,
    "Course": "BSc DS & AI"
}

print("Original Dictionary:", student)

# Access value
print("Name:", student["Name"])

# Add new key
student["College"] = "SDNB Vaishnav College"

# Update value
student["Age"] = 19

# Remove key
student.pop("Course")

# Length
print("Length:", len(student))

# Keys
print("Keys:", student.keys())

# Values
print("Values:", student.values())

# Items
print("Items:", student.items())

# Traverse dictionary
print("Dictionary:")
for key, value in student.items():
    print(key, ":", value)

# Check key
if "Age" in student:
    print("Age key exists")

# Copy dictionary
copy_student = student.copy()
print("Copied Dictionary:", copy_student)

# Clear another dictionary
d = {"A": 1, "B": 2}
d.clear()
print("Cleared Dictionary:", d)

print("Updated Dictionary:", student)

Original Dictionary: {'Name': 'priyadharshini', 'Age': 18, 'Course': 'BSc DS & AI'}
Name: priyadharshini
Length: 3
Keys: dict_keys(['Name', 'Age', 'College'])
Values: dict_values(['priyadharshini', 19, 'SDNB Vaishnav College'])
Items: dict_items([('Name', 'priyadharshini'), ('Age', 19), ('College', 'SDNB Vaishnav College')])
Dictionary:
Name : priyadharshini
Age : 19
College : SDNB Vaishnav College
Age key exists
Copied Dictionary: {'Name': 'priyadharshini', 'Age': 19, 'College': 'SDNB Vaishnav College'}
Cleared Dictionary: {}
Updated Dictionary: {'Name': 'priyadharshini', 'Age': 19, 'College': 'SDNB Vaishnav College'}


In [8]:
practical 7
# File Handling

# Write to file
file = open("sample.txt", "w")
file.write("Welcome to Python\n")
file.write("File Handling Example\n")
file.close()

# Read file
file = open("sample.txt", "r")
print("File Contents:")
print(file.read())
file.close()

# Append data
file = open("sample.txt", "a")
file.write("This is appended text.\n")
file.close()

# Read updated file
file = open("sample.txt", "r")
print("Updated File Contents:")
print(file.read())
file.close()

File Contents:
Welcome to Python
File Handling Example

Updated File Contents:
Welcome to Python
File Handling Example
This is appended text.



In [14]:
practical 8
import numpy as np

# Create two NumPy arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Array A:", a)
print("Array B:", b)

# Arithmetic operations
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# Indexing
print("\nFirst element of Array A:", a[0])

# Slicing
print("Sliced Array A (index 1 to 3):", a[1:4])

# Reshape
c = np.array([1, 2, 3, 4, 5, 6])
d = c.reshape(2, 3)

print("\nReshaped Array:")
print(d)

print("Shape:", d.shape)
print("Dimension:", d.ndim)
print("Size:", d.size)

# Aggregate functions
print("\nSum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

# Universal functions
print("\nSquare Root:", np.sqrt(a))
print("Exponential:", np.exp(a))

# Sorting
print("\nSorted Array A:", np.sort(a))

# Concatenation
concat = np.concatenate((a, b))
print("\nConcatenated Array:", concat)

Array A: [10 20 30 40 50]
Array B: [1 2 3 4 5]

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]

First element of Array A: 10
Sliced Array A (index 1 to 3): [20 30 40]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Size: 6

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]

Sorted Array A: [10 20 30 40 50]

Concatenated Array: [10 20 30 40 50  1  2  3  4  5]


In [16]:
practical 9
import numpy as np

# Create two arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 6, 8, 10])

print("Array A:", a)
print("Array B:", b)

# Arithmetic operations
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# Indexing
print("\nFirst element of A:", a[0])

# Slicing
print("Sliced elements of A (1:4):", a[1:4])

# Reshaping
c = np.array([1, 2, 3, 4, 5, 6])
reshape_array = c.reshape(2, 3)

print("\nReshaped Array:")
print(reshape_array)

print("Shape:", reshape_array.shape)
print("Dimension:", reshape_array.ndim)
print("Size:", reshape_array.size)

# Aggregation operations
print("\nSum:", np.sum(a))
print("Mean:", np.mean(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

# Universal functions
print("\nSquare Root:", np.sqrt(a))
print("Exponential:", np.exp(a))

# Sorting
print("\nSorted Array:", np.sort(a))

#concatenation
concat=np.concatenate((a,b))
print("\nConcatenated Array:",concat)

Array A: [10 20 30 40 50]
Array B: [ 2  4  6  8 10]

Addition: [12 24 36 48 60]
Subtraction: [ 8 16 24 32 40]
Multiplication: [ 20  80 180 320 500]
Division: [5. 5. 5. 5. 5.]

First element of A: 10
Sliced elements of A (1:4): [20 30 40]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Size: 6

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]

Sorted Array: [10 20 30 40 50]

Concatenated Array: [10 20 30 40 50  2  4  6  8 10]


In [17]:
practical 10
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Display the array
print("Array:", arr)

# Sum
print("Sum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Median
print("Median:", np.median(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

# Variance
print("Variance:", np.var(arr))

# Minimum and Maximum
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# Indices of Minimum and Maximum
print("Index of Minimum:", np.argmin(arr))
print("Index of Maximum:", np.argmax(arr))

# Range
print("Range:", np.max(arr) - np.min(arr))

# Percentiles
print("25th Percentile:", np.percentile(arr, 25))
print("50th Percentile:", np.percentile(arr, 50))
print("75th Percentile:", np.percentile(arr, 75))

# Cumulative Sum
print("Cumulative Sum:", np.cumsum(arr))

# Sorted Array
print("Sorted Array:", np.sort(arr))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Minimum: 10
Maximum: 50
Index of Minimum: 0
Index of Maximum: 4
Range: 40
25th Percentile: 20.0
50th Percentile: 30.0
75th Percentile: 40.0
Cumulative Sum: [ 10  30  60 100 150]
Sorted Array: [10 20 30 40 50]
